### ISSUE TITLE
tomorrow's todo list

### ISSUE THREAD

**Issue by tomara-x** [tomara-x/quartz#60]
- [x] one frame button
- [x] yeet the new_lt field
- [x] wh.open inspect
